.prettierignore
Adding files and folders for .prettierignore
=> Adding .prettierignore

package-lock.json, package.json
What's changed
---
- Updating packages
🔥
=> updating packages

src/Components/Feedback.tsx, src/Components/ListState.tsx, src/Components/Router.tsx, src/Components/State.tsx
What's changed
---
- Rewriting component State within new features for React Router v6
- Some enhancements
=> Fixing bug load details state

src/App.scss, src/Components/City/City.tsx
=> Fixing bugs

package-lock.json
=> update: update packages

package-lock.json
Proposal
---
Updating deps for package
=> build(deps): updating dependencies

.dockerignore, .env, .github/workflows/deploy-image.yml, .github/workflows/github-actions-demo.yml, Dockerfile, compose.yml, package-lock.json, package.json
Proposal
---
Creating the context for containerizing app by docker 🐳
=> Dockerizing the application

public/index.html
Has changed
---
- Fixing behavior path for favicon app
=> Fixing favicon path behavior

src/Components/Entry/Entry.spec.tsx, src/Components/Entry/Entry.tsx, src/service/NotifySystem.ts
Has changed
---
- Adding notification system service for the app
- Adjusting tests
=> Adding Notify System

.husky/pre-commit
Has changed
---
- Removing pre-commit instruction in deploying when committing changes.
=> Removing deploy in precommit instruction

package-lock.json, src/Components/ListStates/ListState.tsx
Has changed
=
- Fixing feedback message for the initial screen
- Updating some dependencies
=> refactor: fix feedback message

package-lock.json, src/Components/ListStates/ListState.tsx, tsconfig.json
Has changed
=
- Updating dependencies
- Linting
=> Updating dependencies

src/Components/Cards/Cards.tsx, yarn.lock
What's changed!
=
- Updating packages
=> chore: update packages

src/Components/ListStates/ListState.tsx, src/Components/Search/Search.tsx
What's change
=
- Fixing autocomplete behavior input
=> fix: autocomplete

public/index.html
What's changed
=
- Fix favicon
=> fix: favicon

config/webpack.common.js, config/webpack.dev.js, package.json, yarn.lock
What's new
=
- Fixing the load app in deploy
=> fix: build

src/Components/ListStates/ListState.tsx, src/Components/Search/Search.tsx
What's change
=
- Code improvements
=> feat: improvements

craco.config.cjs
What's change
=
- Improving path deploy
=> feat: ajusts

craco.config.cjs
What's new
=
- Adjust package version
=> feat: adjusts

src/bootstrap.tsx, src/index.tsx
What's change
=
- Importing bootstrap
=> feat: ajust

craco.config.cjs, src/index.tsx
What's changed
=
- Adjust bootstrap import
=> feat: adjust bootstrap

config/webpack.common.ts, public/index.html
What's changed
=
- Adjust favicon
=> fix: adjusting favicon

.gitignore, package.json
What's changed
=
- Update version package.json from v1.5.5 to v1.5.6
#136
=> chore: update version
